### ISSUE TITLE
Don't understand logic for checking whether a "basepath" exists....

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5#117]
Hi, I don't understand this logic:

https://github.com/saalfeldlab/n5/blob/b692b39c3734bc5c2663a4aa1e6704ff4ac327d7/src/main/java/org/janelia/saalfeldlab/n5/N5KeyValueReader.java#L144

Why does it not read: `if (checkExists && !exists(basePath))` instead of `if (checkExists && !exists("/"))`?

I am struggling with this, because I am getting an error:

```
org.janelia.saalfeldlab.n5.N5Exception$N5IOException: No container exists at rawdata/sbem-6dpf-1-whole-raw.n5

	at org.janelia.saalfeldlab.n5.N5KeyValueReader.<init>(N5KeyValueReader.java:144)
	at org.janelia.saalfeldlab.n5.N5KeyValueReader.<init>(N5KeyValueReader.java:86)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.<init>(N5AmazonS3Reader.java:69)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.<init>(N5AmazonS3Reader.java:96)
```

This error is triggered using this code:

```
final AmazonS3 s3 = S3Utils.getS3Client( serviceEndpoint, signingRegion );
this.n5 = new N5AmazonS3Reader( s3, bucketName, key, true );
```

with

<img width="338" alt="image" src="https://github.com/saalfeldlab/n5/assets/2157566/1eca4d66-72ac-4487-bf5a-da6c8d32de2e">

This happens only using the latest versions of n5 that are now shipped with Fiji. Earlier version did not have this issue.

**Comment by tischi** [comment]
Sorry, wrong repo.

**Comment by tischi** [comment]
I arrived at this error using the deprecated `N5AmazonS3Reader`.
Using `N5Factory` instead did not show this issue.
