### ISSUE TITLE
Maven tests fail on windows

### ISSUE THREAD

**Issue by constantinpape** [saalfeldlab/n5#46]
The maven build tests for n5 fail on windows.
These failures actually occurred when trying to build paintera from source on windows 10
and I have only copied the relevant part from the tests here.
Judging from the error message, I would assume there is some issue with `/` vs `\`
Also pinging @hanslovsky.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.janelia.saalfeldlab.util.n5.N5HelpersTest
[ERROR] Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.2 s <<< FAILURE! - in org.janelia.saalfeldlab.util.n5.N5HelpersTest
[ERROR] testListAndSortScaleDatasets(org.janelia.saalfeldlab.util.n5.N5HelpersTest)  Time elapsed: 0.166 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<group[/]s0> but was:<group[\]s0>
        at org.janelia.saalfeldlab.util.n5.N5HelpersTest.testListAndSortScaleDatasets(N5HelpersTest.java:79)

[ERROR] testHighestResolutionDataset(org.janelia.saalfeldlab.util.n5.N5HelpersTest)  Time elapsed: 0.006 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<group[/]s0> but was:<group[\]s0>
        at org.janelia.saalfeldlab.util.n5.N5HelpersTest.testHighestResolutionDataset(N5HelpersTest.java:95)

[INFO] Running org.janelia.saalfeldlab.util.n5.N5TypesTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 s - in org.janelia.saalfeldlab.util.n5.N5TypesTest
[INFO] Running org.janelia.saalfeldlab.util.SetsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.janelia.saalfeldlab.util.SetsTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   N5HelpersTest.testHighestResolutionDataset:95 expected:<group[/]s0> but was:<group[\]s0>
[ERROR]   N5HelpersTest.testListAndSortScaleDatasets:79 expected:<group[/]s0> but was:<group[\]s0>
[INFO]
[ERROR] Tests run: 41, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:25 min
[INFO] Finished at: 2019-01-21T13:20:52+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project paintera: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Software\paintera-master\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

C:\Software\paintera-master>mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\Software\apache-maven-3.6.0\bin\..
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_202\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by hanslovsky** [comment]
That looks like a paintera problem: `N5Helpers.highestResolutionDataset` concatenates group/dataset segments via `Paths.get`, which will insert an operating system dependent directory separator, while the tests concatenates via `/`: `group + "/s0"`. I will have to figure out, which of the two is the appropriate behavior and either change the test (easier) or the affected method(s). For now, I suggest you just skip the tests via the `-DskipTests` flag.

**Comment by hanslovsky** [comment]
What is the exact build command and what is the exact command you run to start paintera? Jar files in Java are similar to `.so`/`.dll` files in the c-world. You need to add all relevant jar files to the `classpath` (`jgo` does that for you). The fat jar profile has been removed in favor of running with `jgo`, so saalfeldlab/paintera#182 should resolve this.

**Comment by hanslovsky** [comment]
> Oh, I was sure this was an n5 issue. Feel free to transfer this to the paintera repo.
@axtimwalde would have  to do this, I do not have admin rights here

**Comment by constantinpape** [comment]
> so [saalfeldlab/paintera#182](https://github.com/saalfeldlab/paintera/issues/182) should resolve this.

Indeed, the failure occurring after skipping the tests is the same issue.

**Comment by axtimwalde** [comment]
Java filesystem ops are supposed to work with "/" cross-platform.  Do not use system specific stuff.  Can this be closed?

**Comment by constantinpape** [comment]
>  Can this be closed?

I mistakenly opened this here because I thought this is an n5 problem.
Turns out it is only an issue with the paintera tests on windows.
Would still be nice to have this fixed though, so ideally you would [transfer](https://help.github.com/articles/transferring-an-issue-to-another-repository/) this issue to paintera.
