### ISSUE TITLE
Intermittent exception in deepList

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5#82]
appears to happen when the `pathName` argument is empty, and the line with comment `//skip self` does not return the 'self' path. 

https://github.com/saalfeldlab/n5/blob/0ba19459a3d0fd447b5b6b5aa5b10f2e3acc06b3/src/main/java/org/janelia/saalfeldlab/n5/N5Reader.java#L501-L505

```
deep list
   deep list result: /s1
   deep list result: /s0
   deep list result: 
```

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at org.janelia.saalfeldlab.n5.N5Reader.deepList(N5Reader.java:507)
	at org.janelia.saalfeldlab.n5.N5Reader.deepList(N5Reader.java:530)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer.discoverAndParseRecursive(N5DatasetDiscoverer.java:393)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer.discoverAndParseRecursive(N5DatasetDiscoverer.java:378)
	at org.janelia.saalfeldlab.n5.N5DatasetDiscoverer.discoverAndParseRecursive(N5DatasetDiscoverer.java:371)
	at org.janelia.saalfeldlab.n5.metadata.MetadataTests.testEmptyBase(MetadataTests.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by bogovicj** [comment]
probably not a deeplist issue
